### ISSUE TITLE
Nesse item “Descrição de materiais e métodos:” colocar numero máximo de caracteres

### ISSUE THREAD

**Issue by GuilhermeGz** [lmtsufape/CEUA-Ufape#54]

**Comment by Edgarvital** [comment]
![Image](https://user-images.githubusercontent.com/20988585/193432263-8ec09a2d-e16a-446f-bea7-14de63183b8c.png)

**Comment by GuilhermeGz** [comment]
Adicionado limite de 1000 caracteres
